name: first workflow

on:
  push:
    branches:
      - main
jobs:
    example-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print a welcome message
          run: echo "welcome to our first Github workflow"
        - name: Checkout repository
          uses: actions/checkout@v4.2.2
        - name: List repository files
          run: ls -la
        - name: mkdir
          run: mkdir test
          
